// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireapp

import (
	"github.com/khanakia/mangocms/mango/cli"
	"github.com/khanakia/mangocms/mango/configmgr"
	"github.com/khanakia/mangocms/mango/dbconn"
	"github.com/khanakia/mangocms/mango/gormdb"
	"github.com/khanakia/mangocms/mango/natso"
	"github.com/ubgo/gofm/logger"
)

// Injectors from wireapp.go:

func Init() Plugin {
	config := NewConfigMgrConfig()
	configMgr := configmgr.New(config)
	cliCli := cli.New()
	loggerLogger := logger.New()
	dbconnConfig := dbconn.Config{
		ConfigMgr: configMgr,
	}
	dbConn := dbconn.New(dbconnConfig)
	gormdbConfig := NewGormConfig(dbConn)
	gormDB := gormdb.New(gormdbConfig)
	natsoConfig := natso.Config{
		Cli: cliCli,
	}
	natsoNatso := natso.New(natsoConfig)
	plugin := Plugin{
		ConfigMgr: configMgr,
		Cli:       cliCli,
		Logger:    loggerLogger,
		DbConn:    dbConn,
		GormDB:    gormDB,
		Natso:     natsoNatso,
	}
	return plugin
}

// wireapp.go:

func NewGormConfig(dbConn dbconn.DbConn) gormdb.Config {
	return gormdb.Config{
		DB: dbConn.SqlDb,
	}
}

func NewConfigMgrConfig() configmgr.Config {
	return configmgr.Config{}
}
